// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUFMB0tMrlgEPWw6i1ZI7Fq5dU67OKMww',
    appId: '1:570470433164:web:8fb5138732af265905d6a9',
    messagingSenderId: '570470433164',
    projectId: 'parkwaze-38a5a',
    authDomain: 'parkwaze-38a5a.firebaseapp.com',
    storageBucket: 'parkwaze-38a5a.appspot.com',
    measurementId: 'G-T555SZG5TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGUCG8o8t31JNwletUlGOt1eUgafC8QJA',
    appId: '1:570470433164:android:1d5027f906d20ef505d6a9',
    messagingSenderId: '570470433164',
    projectId: 'parkwaze-38a5a',
    storageBucket: 'parkwaze-38a5a.appspot.com',
  );
}
